### PR TITLE
Added option to set kubernetes cluster hostname

### PR DESCRIPTION
**Pull request by codedninja**

### CODE REVIEW

**Comment by travisghansen** [comment]
This is an interesting issue. I think I’ll actually fix the bug in the underlying client code and then this will inherit the fix (after updating the dep).

**Comment by codedninja** [comment]
Was trying to deploy under a Rancher cluster and the hostname scheme is different than `kubernetes.default.svc` but in Rancher it's the following `kubernetes.default.svc.cluster.local`

**Comment by codedninja** [comment]
Was trying to deploy under a Rancher cluster and the hostname scheme is different than `kubernetes.default.svc` that is set in "
kubernetes-client-php ". Rancher's service discovery scheme is following `kubernetes.default.svc.cluster.local`

**Comment by travisghansen** [comment]
That should still resolve. What’s the value of the env var in the pod?

**Comment by travisghansen** [comment]
This has been fixed in the underlying code now in `v0.4.0` rendering this PR unnecessary. Try it out and let me know if you run into any issues.

**Pull request closed without merging**
